import { PRODUCT_OPTIONS } from './product-options';
import type { ProductFormInput, ProductOptionInput } from './product-record';

/**
 * 상품 옵션 시드를 폼 입력 형태로 옮긴다.
 * 판매 화면(`lib/data/product-options.ts`)과 등록 폼이 **같은 옵션**을 보게 하기 위해서다.
 */
function optionsOf(productId: string): {
  colors: string[];
  sizes: string[];
  options: ProductOptionInput[];
} {
  const rows = PRODUCT_OPTIONS.filter((option) => option.productId === productId);
  return {
    colors: [...new Set(rows.map((option) => option.color))],
    sizes: [...new Set(rows.map((option) => option.size))].filter(Boolean),
    options: rows.map((option) => ({
      key: `${option.color}|${option.size}`,
      color: option.color,
      size: option.size,
      stock: `${option.stock}`,
    })),
  };
}

export type ProductRecord = ProductFormInput & {
  id: string;
  createdAt: string;
  /** 누적 판매량 — NEW·BEST 자동 분류의 입력값이다 (lib/data/product-tags.ts) */
  salesCount: number;
};

/**
 * 프론트엔드 전용 시드 데이터.
 * 목록 화면과 상세(등록·수정) 화면이 **같은 배열**을 본다.
 */
export const PRODUCTS: ProductRecord[] = [
  {
    id: 'P-1042',
    createdAt: '2026-08-01',
    salesCount: 482,
    name: '리넨 오버셔츠',
    categoryRootId: 'C-05',
    categoryChildId: 'C-06',
    saleState: '판매중',
    price: '49000',
    listPrice: '59000',
    stock: '120',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [
      { key: 'r1', name: '제주', fee: '3000' },
      { key: 'r2', name: '도서산간', fee: '5000' },
    ],
    description: '가볍고 통기성이 좋은 여름용 셔츠입니다.',
    visible: true,
    ...optionsOf('P-1042'),
  },
  {
    id: 'P-1041',
    createdAt: '2026-07-30',
    salesCount: 37,
    name: '휴대용 커피 그라인더',
    categoryRootId: 'C-01',
    categoryChildId: 'C-02',
    saleState: '판매대기',
    price: '78000',
    listPrice: '',
    stock: '32',
    rewardKind: '정액',
    rewardValue: '2000',
    shippingPolicy: '무료',
    shippingFee: '0',
    freeThreshold: '',
    regions: [{ key: 'r1', name: '도서산간', fee: '5000' }],
    description: '수동식 원뿔 버 그라인더입니다.',
    visible: true,
    ...optionsOf('P-1041'),
  },
  {
    id: 'P-1040',
    createdAt: '2026-07-28',
    salesCount: 156,
    name: '워시드 코튼 침구 세트',
    categoryRootId: 'C-01',
    categoryChildId: 'C-03',
    saleState: '판매중',
    price: '128000',
    listPrice: '148000',
    stock: '8',
    rewardKind: '정률',
    rewardValue: '3',
    shippingPolicy: '유료',
    shippingFee: '4000',
    freeThreshold: '',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1040'),
  },
  {
    id: 'P-1039',
    createdAt: '2026-07-25',
    salesCount: 214,
    name: '접이식 캠핑 체어',
    categoryRootId: 'C-01',
    categoryChildId: 'C-04',
    saleState: '판매중지',
    price: '54000',
    listPrice: '',
    stock: '0',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [],
    description: '',
    visible: false,
    ...optionsOf('P-1039'),
  },
  {
    id: 'P-1038',
    createdAt: '2026-07-29',
    salesCount: 186,
    name: '오크 4인 식탁 세트',
    categoryRootId: 'C-01',
    categoryChildId: 'C-04',
    saleState: '판매중',
    price: '389000',
    listPrice: '459000',
    stock: '12',
    rewardKind: '정률',
    rewardValue: '3',
    shippingPolicy: '유료',
    shippingFee: '4000',
    freeThreshold: '',
    regions: [],
    description: '<p>원목 상판에 철제 프레임을 더했습니다.</p>',
    visible: true,
    ...optionsOf('P-1038'),
  },
  {
    id: 'P-1037',
    createdAt: '2026-08-02',
    salesCount: 312,
    name: '구스 이불 세트',
    categoryRootId: 'C-01',
    categoryChildId: 'C-03',
    saleState: '판매중',
    price: '219000',
    listPrice: '289000',
    stock: '26',
    rewardKind: '정률',
    rewardValue: '3',
    shippingPolicy: '무료',
    shippingFee: '0',
    freeThreshold: '',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1037'),
  },
  {
    id: 'P-1036',
    createdAt: '2026-07-31',
    salesCount: 48,
    name: '린넨 커튼 2장',
    categoryRootId: 'C-01',
    categoryChildId: 'C-03',
    saleState: '판매중',
    price: '68000',
    listPrice: '',
    stock: '54',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1036'),
  },
  {
    id: 'P-1035',
    createdAt: '2026-08-01',
    salesCount: 96,
    name: '무드 플로어 조명',
    categoryRootId: 'C-01',
    categoryChildId: 'C-02',
    saleState: '판매중',
    price: '129000',
    listPrice: '159000',
    stock: '18',
    rewardKind: '정률',
    rewardValue: '3',
    shippingPolicy: '무료',
    shippingFee: '0',
    freeThreshold: '',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1035'),
  },
  {
    id: 'P-1034',
    createdAt: '2026-06-20',
    salesCount: 420,
    name: '스테인리스 밀폐용기 6P',
    categoryRootId: 'C-01',
    categoryChildId: 'C-02',
    saleState: '판매중',
    price: '36500',
    listPrice: '52000',
    stock: '140',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1034'),
  },
  {
    id: 'P-1033',
    createdAt: '2026-08-02',
    salesCount: 22,
    name: '와플 코튼 로브',
    categoryRootId: 'C-05',
    categoryChildId: 'C-07',
    saleState: '판매중',
    price: '59000',
    listPrice: '',
    stock: '33',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1033'),
  },
  {
    id: 'P-1032',
    createdAt: '2026-05-14',
    salesCount: 268,
    name: '경량 다운 베스트',
    categoryRootId: 'C-05',
    categoryChildId: 'C-06',
    saleState: '판매중',
    price: '119000',
    listPrice: '149000',
    stock: '21',
    rewardKind: '정률',
    rewardValue: '3',
    shippingPolicy: '무료',
    shippingFee: '0',
    freeThreshold: '',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1032'),
  },
  {
    id: 'P-1031',
    createdAt: '2026-08-03',
    salesCount: 18,
    name: '코튼 파자마 세트',
    categoryRootId: 'C-05',
    categoryChildId: 'C-07',
    saleState: '판매중',
    price: '49000',
    listPrice: '',
    stock: '64',
    rewardKind: '정률',
    rewardValue: '1',
    shippingPolicy: '조건부 무료',
    shippingFee: '3000',
    freeThreshold: '50000',
    regions: [],
    description: '',
    visible: true,
    ...optionsOf('P-1031'),
  },
];

export function findProduct(id: string): ProductRecord | undefined {
  return PRODUCTS.find((product) => product.id === id);
}

/** 상품 코드는 사람이 정하지 않는다 — 등록 화면에 자동 생성된 값을 보여 준다. */
export function nextProductCode(products: ProductRecord[] = PRODUCTS): string {
  const max = products.reduce((biggest, product) => Math.max(biggest, Number(product.id.replace('P-', ''))), 1000);
  return `P-${max + 1}`;
}
